const certz3 = [
    "Meta_front_end_developer.avif",
    "Capstonr retrieving, processing and visualizing data w python Cert 5-1.avif",
    "Arthur Modyman IV-JustJavaScript.com-certificate-1.avif",
    "CertificateOfCompletion_Advanced Express-1.avif",
    "CertificateOfCompletion_Advanced Node.js-1.avif",
    "CertificateOfCompletion_Advanced npm-1.avif",
    "CertificateOfCompletion_Become a BackEnd Web Developer-1.avif",
    "CertificateOfCompletion_Become a FullStack Web Developer-1.avif",
    "CertificateOfCompletion_Become a JavaScript Developer-1.avif",
    "CertificateOfCompletion_Become a React Developer-1.avif",
    "CertificateOfCompletion_Building RESTful APIs with Node.js and Express-1.avif",
    "CertificateOfCompletion_Building a Website with Node.js and Express.js-1.avif",
    "CertificateOfCompletion_CSS Essential Training-1.avif",
    "CertificateOfCompletion_Creating a Serverless Application Using React in AWS-1.avif",
    "CertificateOfCompletion_Databases for Node.js Developers-1.avif",
    "CertificateOfCompletion_DevOps Foundations-1.avif",
    "CertificateOfCompletion_Developing for Web Performance-1.avif",
    "CertificateOfCompletion_Explore Web Development with Node.js-1.avif",
    "CertificateOfCompletion_Express Essential Training-1.avif",
    "CertificateOfCompletion_Express Essential Training2-1.avif",
    "CertificateOfCompletion_HTML Essential Training-1.avif",
    "CertificateOfCompletion_HTTP Essential Training-1.avif",
    "CertificateOfCompletion_JSON Essential Training-1.avif",
    "CertificateOfCompletion_JavaScript Async-1.avif",
    "CertificateOfCompletion_JavaScript Best Practices for Data-1.avif",
    "CertificateOfCompletion_JavaScript Classes-1.avif",
    "CertificateOfCompletion_JavaScript Code Challenges-1.avif",
    "CertificateOfCompletion_JavaScript Essential Training-1.avif",
    "CertificateOfCompletion_JavaScript Functions-1.avif",
    "CertificateOfCompletion_JavaScript Modern Browser APIs-1.avif",
    "CertificateOfCompletion_JavaScript Patterns-1.avif",
    "CertificateOfCompletion_Learning ECMAScript 6 ES6-1.avif",
    "CertificateOfCompletion_Learning FullStack JavaScript Development MongoDB Node and React-1.avif",
    "CertificateOfCompletion_Learning Functional Programming with JavaScript ES5-1.avif",
    "CertificateOfCompletion_Learning Functional Programming with JavaScript ES6-1.avif",
    "CertificateOfCompletion_Learning MongoDB-1.avif",
    "CertificateOfCompletion_Learning Node.js-1.avif",
    "CertificateOfCompletion_Learning REST APIs-1.avif",
    "CertificateOfCompletion_Learning React.js-1.avif",
    "CertificateOfCompletion_Learning npm the Node Package Manager-1.avif",
    "CertificateOfCompletion_MERN Essential Training-1.avif",
    "CertificateOfCompletion_NoSQL Essential Training-1.avif",
    "CertificateOfCompletion_Node.js Essential Training-1.avif",
    "CertificateOfCompletion_Node.js Microservices-1.avif",
    "CertificateOfCompletion_Node.js RealTime Web with Socket.IO-1.avif",
    "CertificateOfCompletion_Node.js Securing RESTful APIs-1.avif",
    "CertificateOfCompletion_Node.js Security-1.avif",
    "CertificateOfCompletion_Node.js Testing and Code Quality-1.avif",
    "CertificateOfCompletion_Programming Foundations Web Security-1.avif",
    "CertificateOfCompletion_React Context API Development-1.avif",
    "CertificateOfCompletion_React Creating and Hosting a FullStack Site-1.avif",
    "CertificateOfCompletion_React Ecosystems-1.avif",
    "CertificateOfCompletion_React Hooks-1.avif",
    "CertificateOfCompletion_React SPAs-1.avif",
    "CertificateOfCompletion_React Working with APIs-1.avif",
    "CertificateOfCompletion_React.js Essential Training-1.avif",
    "CertificateOfCompletion_SQL Essential Training-1.avif",
    "CertificateOfCompletion_Search Techniques for Web Developers-1.avif",
    "CertificateOfCompletion_TypeScript ObjectOriented Programming-1.avif",
    "Coursera Certificate 1-1.avif",
    "FE web UI frameworks and tools BS4-1.avif",
    "Python Data Structures Coursera Cert 2 -1.avif",
    "Python to access web data Cert 3-1.avif",
    "React js Building an Interface-1.avif",
    "Udemy 11 js features-1.avif",
    "Using Databases w Python Cert 4-1.avif",
    "devops scripting w python spec cert-1.avif",
    "js masterclass cert-1.avif",
    "python specialization cert-1.avif"
];